[package]
name = "rust_cli"
version = "0.1.0"
edition = "2024"
authors = ["james_hzq"]

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.48", features = ["derive"] }
csv = "1.3.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
